In [22]:
import numpy as np

In [19]:
#Задача 1
N=int(input())
a = np.arange(0, N)
print(list(reversed(a)))

5
[4, 3, 2, 1, 0]


In [21]:
#Задача 2
N=int(input())
matrix=np.diag(np.arange(N,0,-1))
summ=0
for line in matrix:
    for j in line:
        summ+=j
print('сумма: {}'.format(summ))
print (matrix)

3
сумма: 6
[[3 0 0]
 [0 2 0]
 [0 0 1]]


In [25]:
#Задача 3
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4]] )
b = np.array( [4, 12, -3] )

In [26]:
from numpy import linalg

In [28]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [29]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [30]:
#Задача 4
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [31]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [33]:
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [34]:
def cosine( users_stats, next_user_stats ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    users_statsLength = np.linalg.norm( users_stats )
    next_user_statsLength = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_statsLength * next_user_statsLength )

In [54]:
cosinus = np.array([cosine(line, next_user_stats) for line in users_stats])
cosinus

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [53]:
best_user = np.argmax(cosinus)
print ('Самый похожий пользователь c Id: ', best_user+1)

Самый похожий пользователь c Id:  8
